export const FETCH_ALL_BOOKS = 'FETCH_ALL_BOOKS'
export const FETCH_ALL_BOOKS_SUCCESS = 'FETCH_ALL_BOOKS_SUCCESS'
export const CHANGE_BOOK_SHELF = 'CHANGE_BOOK_SHELF'
export const CHANGE_BOOK_SHELF_SUCCESS = 'CHANGE_BOOK_SHELF_SUCCESS'